### ISSUE TITLE
How to debug backup solution with amazon s3

### ISSUE THREAD

**Issue by mac-lucky** [cscetbon/casskop#122] opened 2023-07-14 12:08 UTC
## Type of question

how to implement a specific feature

## Question

**What did you do?**
cassandra-backup.yml
```
apiVersion: db.orange.com/v2
kind: CassandraBackup
metadata:
  name: daily-cassandra-backup
  namespace: cassandra
  labels:
    app: cassandra
spec:
  cassandraCluster: cassandra
  datacenter: datacenter1
  storageLocation: s3://backups-dev
  snapshotTag: daily
  secret: cassandra-dev-s3-backup-secret
  schedule: "@daily"
```

cassandra-dev-s3-backup-secret.yml:
```
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-dev-s3-backup-secret
  namespace: cassandra
type: Opaque
stringData:
  awsaccesskeyid: <keyid>
  awssecretaccesskey: <secret>
  awsregion: eu-central-1
  awsendpoint: https://s3.eu-central-1.amazonaws.com
```

**What did you expect to see?**
I see this in CassandraBackup CRD with all the Annotations, but I don't know how to verify if it actually works. No file is created in AWS bucket.

**What did you see instead? Under which circumstances?**
No data in AWS, no events for created backup CRD

**Environment**
* casskop version: 

2.1.17

* Kubernetes version information:

Kustomize Version: v5.0.1
Server Version: v1.25.9+k3s1

* Kubernetes cluster kind: 

k3s - 3 master 6 workers

* Cassandra version:

3.11.3

replicas: 3

**Comment by mac-lucky** [comment] 2023-07-17 12:34
I got it working by changing name of cassandra cluster and the events show properly, but backup is still having problems cause of not specified --data-dir:
```
12:33:05.670 ERROR com.instaclustr.operations.Operation - Reporting errors for operation d3f8f0a3-13b8-4b4f-915f-934955e5e18b
12:33:05.670 ERROR com.instaclustr.operations.Operation - --- start of error reporting ---
12:33:05.670 ERROR com.instaclustr.operations.Operation - Error{source=cassandra-opt-datacenter1-rack1-1, message=You have not specified any --data-dir on command line or respective field in JSON request., throwable=java.lang.IllegalStateException: You have not specified any --data-dir on command line or respective field in JSON request.}
java.lang.IllegalStateException: You have not specified any --data-dir on command line or respective field in JSON request.
	at com.instaclustr.esop.impl.backup.BackupOperationRequest.validate(BackupOperationRequest.java:177)
	at com.instaclustr.esop.impl.backup.BackupOperation.run0(BackupOperation.java:131)
	at com.instaclustr.operations.Operation.run(Operation.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
12:33:05.674 ERROR com.instaclustr.operations.Operation - --- end of error reporting ---
```

How to fix this?

**Comment by mac-lucky** [comment] 2023-07-17 12:35
I got it working by changing name of cassandra cluster and the events show properly, but backup is still having problems cause of not specified --data-dir:
```
12:33:05.670 ERROR com.instaclustr.operations.Operation - Reporting errors for operation d3f8f0a3-13b8-4b4f-915f-934955e5e18b
12:33:05.670 ERROR com.instaclustr.operations.Operation - --- start of error reporting ---
12:33:05.670 ERROR com.instaclustr.operations.Operation - Error{source=cassandra-opt-datacenter1-rack1-1, message=You have not specified any --data-dir on command line or respective field in JSON request., throwable=java.lang.IllegalStateException: You have not specified any --data-dir on command line or respective field in JSON request.}
java.lang.IllegalStateException: You have not specified any --data-dir on command line or respective field in JSON request.
	at com.instaclustr.esop.impl.backup.BackupOperationRequest.validate(BackupOperationRequest.java:177)
	at com.instaclustr.esop.impl.backup.BackupOperation.run0(BackupOperation.java:131)
	at com.instaclustr.operations.Operation.run(Operation.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
12:33:05.674 ERROR com.instaclustr.operations.Operation - --- end of error reporting ---
```

How to fix this?

**Comment by cscetbon** [comment] 2023-08-18 04:01
Sorry @mac-lucky I've been away for some time. Looking into it.. Any information in the events besides those logs ?

@AKamyshnikova do you think it's been caused by the upgrade then downgrade ? Do you have the same issue ?
I see that we haven't created a version containing
```
* [e2e tests] Fix api version for casskop custom resources by @AKamyshnikova in https://github.com/cscetbon/casskop/pull/119
* Revert "Update instaclustr-icarus to 2.0.4" by @AKamyshnikova in https://github.com/cscetbon/casskop/pull/121
```

and I wonder if this is why.

**Comment by AKamyshnikova** [comment] 2023-08-18 09:31
@cscetbon I hoped we merge https://github.com/cscetbon/casskop/pull/120 and create new release

**Comment by mac-lucky** [comment] 2023-08-18 10:25
In events i got 
```Backup operation 8bf7508b-242b-4a5a-bc7a-0d2af4c5f1d7 on node cassandra-opt-datacenter1-rack1-1 has failed```

and the logs again from backrest-sidecar:
```
10:24:14.318 ERROR com.instaclustr.operations.Operation - Error{source=cassandra-opt-datacenter1-rack1-0, message=You have not specified any --data-dir on command line or respective field in JSON request., throwable=java.lang.IllegalStateException: You have not specified any --data-dir on command line or respective field in JSON request.}
java.lang.IllegalStateException: You have not specified any --data-dir on command line or respective field in JSON request.
	at com.instaclustr.esop.impl.backup.BackupOperationRequest.validate(BackupOperationRequest.java:177)
	at com.instaclustr.esop.impl.backup.BackupOperation.run0(BackupOperation.java:131)
	at com.instaclustr.operations.Operation.run(Operation.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
10:24:14.318 ERROR com.instaclustr.operations.Operation - --- end of error reporting ---
```

**Comment by cscetbon** [comment] 2023-08-23 00:09
Yeah @mac-lucky that makes sense and seems related to what @AKamyshnikova was talking about. We need to create a new release and will do soon

**Comment by mac-lucky** [comment] 2023-09-01 11:00
I see there is new version released, but I don't see any new helm chart? Is there some CI/CD for this or You build this manually? :)

**Comment by cscetbon** [comment] 2023-09-08 04:03
> Everything is functioning well now.

@mac-lucky glad to hear ! 

>  When a backup is created daily, does it have a retention period or is it overwritten each day? Based on my observation, it seems to be the latter option. Could you please confirm this?


So backup are not actually cleaned. Files are not overwritten if they still exist when the next backup happens but their metadata is updated. That way if you use [AWS S3 Lifecycle](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html) for instance to clean up older files, those files won't be deleted as they were just updated (only their metadata) recently. To read more about it checkout [esop's documentation](https://github.com/instaclustr/esop#skipping-refreshment-of-remote-objects) as it uses Icarus under the hood which is what CassKop uses as well

**Comment by mac-lucky** [comment] 2023-09-08 06:38
@cscetbon Thank you, I read it. So if I would like to have a backup from 7 days I need 7 buckets and 7 jobs with backup?

**Comment by cscetbon** [comment] 2023-09-08 13:07
Fortunately not ! You just take a daily backup (for instance by setting `schedule: "@midnight"` in your CassandraBackup object) and create an s3 lifecycle policy that gets rid of files that are older than 7 days (check out [this blog post](https://lepczynski.it/en/aws_en/automatically-delete-old-files-from-aws-s3/))

**Comment by mac-lucky** [comment] 2023-09-08 14:14
Last question. How do I recover backup from 3 days ago?  Can I specify backup timestamp?
```
apiVersion: db.orange.com/v2
kind: CassandraRestore
metadata:
  name: nightly-cassandra-backup
  labels:
    app: cassandra
spec:
  cassandraBackup: nightly-cassandra-backup
  cassandraCluster: test-cluster
```

**Comment by cscetbon** [comment] 2023-09-08 16:10
You you can't recover a backup to a specific date but only to the last version of it. If you want to be able to choose which day to pick, then you need one CassandraBackup per day instead.
So you could have one for Monday, one for Tuesday, one for Wednesday, etc... each one scheduled on a specific day only and then you can choose the exact one you want to restore.

**Comment by cscetbon** [comment] 2023-09-13 04:32
Closing this request as questions got answered

**Closed** 2023-09-13 04:32 UTC
